linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - errorlint

dupl:
  threshold: 200
exhaustive:
  default-signifies-exhaustive: false
gci:
  local-prefixes: github.com/golangci/golangci-lint
goconst:
  min-len: 2
  min-occurrences: 2
gocritic:
  enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
  disabled-checks:
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - ifElseChain
    - octalLiteral
    - whyNoLint
    - wrapperFunc
gocyclo:
  min-complexity: 15
goimports:
  local-prefixes: github.com/golangci/golangci-lint
gomnd:
  settings:
    mnd:
      # don't include the "operation" and "assign"
      checks: argument,case,condition,return
govet:
  check-shadowing: true
  settings:
    printf:
      funcs:
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
lll:
  line-length: 160
misspell:
  locale: US
nolintlint:
  allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
  allow-unused: false # report any unused nolint directives
  require-explanation: false # don't require an explanation for nolint directives
  require-specific: false # don't require nolint directives to be specific about which linter is being skipped


output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: tab

issues:
  exclude-use-default: false
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

# all available settings of specific linters
linters-settings:
  lll:
    line-length: 160
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false
  stylecheck:
    # exclude ST1016 because of autogenerated files to interact with DB
    # "methods on the same type should have the same receiver name"
    checks: [ "all", "-ST1016" ]
  funlen:
    lines: 100
    statements: 50

run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 30m
  allow-parallel-runners: true
  skip-dirs-use-default: true
  concurrency: 5
  skip-dirs:
    - ./pkg/proto
    - ./internal/mocks
